### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by AVIATORJENN** [SilentGhostX/HT-WPS-Breaker#6]
I go through the steps and everything g works fine up until it's time to start the cracking. Once I've selected a network to hack, it says wait until the required arguments are captured and then it says failed to associate with that specific network. Is there any way to fix that?

**Comment by 0E800** [comment]
Its most likely because you are too far away or you wifi device does not
support monitor mode / packet injection. Ive been using this helper script
for some months now and it works.

On Thu, Dec 10, 2015 at 11:23 PM, AVIATORJENN notifications@github.com
wrote:

> I go through the steps and everything g works fine up until it's time to
> start the cracking Once I've selected a network to hack, it says wait until
> the required arguments are captured and then it says failed to associate
> with that specific network Is there any way to fix that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SilentGhostX/HT-WPS-Breaker/issues/6.

## 

[image: --]
0E 800
[image: http://]about.me/oe800
http://about.me/oe800
